[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sentinelsniff"
version = "2.0.0"
description = "Professional Network Traffic Anomaly Detection & Forensics Engine"
license = "MIT"
authors = [{ name = "Deepesh Kumar Mahawar", email = "deepeshmahawar2006@gmail.com" }]
keywords = ["cybersecurity", "network", "packet-analysis", "sniffer", "soc", "mitre-attack"]
classifiers = ["Programming Language :: Python :: 3", "Topic :: Security"]
requires-python = ">=3.10"
dependencies = ["scapy>=2.5.0"]

[project.scripts]
sentinelsniff = "sentinelsniff.cli:main"

[project.urls]
Homepage = "https://github.com/deepmaha2006/SentinelSniff"

[tool.setuptools.packages.find]
include = ["sentinelsniff*"]

[tool.black]
line-length = 100
target-version = ["py310"]
